# Generated by Django 5.1 on 2025-02-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
    ]
